version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    #ports:
    #  - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rustweb"]
      interval: 10s
      timeout: 5s
      retries: 25

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./robocert/wait-for-robocert.sh:/wait-for-robocert.sh # Mount the wait script
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./robocert/letsencrypt:/etc/letsencrypt
      - ./robocert/dnsrobocert:/etc/dnsrobocert
    depends_on:
      - robocert
    command: [ "/bin/sh", "-c", "chmod +x /wait-for-robocert.sh && /wait-for-robocert.sh" ] # Override the default command

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SQLX_OFFLINE=${SQLX_OFFLINE}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SALT=${SALT}
    depends_on:
      postgres:
        condition: service_healthy



  robocert:
    image: adferrand/dnsrobocert
    container_name: robocert
    volumes:
      - ./robocert/letsencrypt:/etc/letsencrypt
      - ./robocert/dnsrobocert:/etc/dnsrobocert
    environment:
      - VERSION=latest
    restart: always


volumes:
  db:
    driver: local